### ISSUE TITLE
[BE] Github Actions Workflows 생성 및 무중단 배포 테스트

### ISSUE THREAD

**Issue by HanYoonSoo** [hobbytrip/hobbytrip#107]
## 작업 대상
- Github Actions Secrets 환경변수 등록
- 서비스 별 Github Actions Workflow 생성
- Git 서브모듈 .gitmoudles에 등록
- 무중단 배포 테스트

## 작업 세부 설명
- [x] GCP 관련 환경변수(Host, Username, Key)
- [x] Docker 관련 환경변수(Username, Password)
- [x] 서비스별 디렉토리 파일 변경을 확인하여 무중단 배포 진행
- [x] CI/CD YAML 파일 작성(아래 첨부)

```yaml
name: CommunityService CI/CD

on:
  push:
    branches:
      - 'BE/dev'
    paths:
      - 'src/backend/community-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
          
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.COMMUNITY_ACTION_TOKEN }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x src/backend/community-service/gradlew

      - name: Project Build
        env:
          jasypt.encryptor.password: ${{ secrets.JASYPT_PASSWORD }}
        working-directory: ./src/backend/community-service
        run: ./gradlew clean build
        shell: bash

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/community-service:1.0 ./src/backend/community-service

      - name: Docker Image Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/community-service:1.0

      - name: GCP 인스턴스 접속 및 무중단 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /script
            make community-update
```  
- [x] 무중단 배포 성공
